/**
 * This class is generated by jOOQ
 */
package com.example.project.db.mysql;


import com.example.project.db.mysql.tables.Author;
import com.example.project.db.mysql.tables.Book;
import com.example.project.db.mysql.tables.BookStore;
import com.example.project.db.mysql.tables.BookToBookStore;
import com.example.project.db.mysql.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Aber extends SchemaImpl {

	private static final long serialVersionUID = -800873694;

	/**
	 * The reference instance of <code>aber</code>
	 */
	public static final Aber ABER = new Aber();

	/**
	 * No further instances allowed
	 */
	private Aber() {
		super("aber");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Author.AUTHOR,
			Book.BOOK,
			BookStore.BOOK_STORE,
			BookToBookStore.BOOK_TO_BOOK_STORE,
			User.USER);
	}
}
