/**
 * This class is generated by jOOQ
 */
package com.example.project.db.mysql;


import com.example.project.db.mysql.tables.Author;
import com.example.project.db.mysql.tables.Book;
import com.example.project.db.mysql.tables.BookStore;
import com.example.project.db.mysql.tables.BookToBookStore;
import com.example.project.db.mysql.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in aber
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table aber.author
	 */
	public static final Author AUTHOR = com.example.project.db.mysql.tables.Author.AUTHOR;

	/**
	 * The table aber.book
	 */
	public static final Book BOOK = com.example.project.db.mysql.tables.Book.BOOK;

	/**
	 * The table aber.book_store
	 */
	public static final BookStore BOOK_STORE = com.example.project.db.mysql.tables.BookStore.BOOK_STORE;

	/**
	 * The table aber.book_to_book_store
	 */
	public static final BookToBookStore BOOK_TO_BOOK_STORE = com.example.project.db.mysql.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

	/**
	 * The table aber.user
	 */
	public static final User USER = com.example.project.db.mysql.tables.User.USER;
}
