/**
 * This class is generated by jOOQ
 */
package com.example.project.db.mysql.tables;


import com.example.project.db.mysql.Aber;
import com.example.project.db.mysql.Keys;
import com.example.project.db.mysql.tables.records.BookRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book extends TableImpl<BookRecord> {

	private static final long serialVersionUID = 2065701037;

	/**
	 * The reference instance of <code>aber.book</code>
	 */
	public static final Book BOOK = new Book();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BookRecord> getRecordType() {
		return BookRecord.class;
	}

	/**
	 * The column <code>aber.book.id</code>.
	 */
	public static final TableField<BookRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), BOOK, "");

	/**
	 * The column <code>aber.book.author_id</code>.
	 */
	public static final TableField<BookRecord, Integer> AUTHOR_ID = createField("author_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), BOOK, "");

	/**
	 * The column <code>aber.book.co_author_id</code>.
	 */
	public static final TableField<BookRecord, Integer> CO_AUTHOR_ID = createField("co_author_id", org.jooq.impl.SQLDataType.INTEGER, BOOK, "");

	/**
	 * The column <code>aber.book.details_id</code>.
	 */
	public static final TableField<BookRecord, Integer> DETAILS_ID = createField("details_id", org.jooq.impl.SQLDataType.INTEGER, BOOK, "");

	/**
	 * The column <code>aber.book.title</code>.
	 */
	public static final TableField<BookRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), BOOK, "");

	/**
	 * The column <code>aber.book.published_in</code>.
	 */
	public static final TableField<BookRecord, Integer> PUBLISHED_IN = createField("published_in", org.jooq.impl.SQLDataType.INTEGER, BOOK, "");

	/**
	 * The column <code>aber.book.language_id</code>.
	 */
	public static final TableField<BookRecord, Integer> LANGUAGE_ID = createField("language_id", org.jooq.impl.SQLDataType.INTEGER, BOOK, "");

	/**
	 * The column <code>aber.book.rec_version</code>.
	 */
	public static final TableField<BookRecord, Integer> REC_VERSION = createField("rec_version", org.jooq.impl.SQLDataType.INTEGER, BOOK, "");

	/**
	 * The column <code>aber.book.rec_timestamp</code>.
	 */
	public static final TableField<BookRecord, Timestamp> REC_TIMESTAMP = createField("rec_timestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), BOOK, "");

	/**
	 * No further instances allowed
	 */
	private Book() {
		this("book", null);
	}

	private Book(String alias, Table<BookRecord> aliased) {
		this(alias, aliased, null);
	}

	private Book(String alias, Table<BookRecord> aliased, Field<?>[] parameters) {
		super(alias, Aber.ABER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<BookRecord> getPrimaryKey() {
		return Keys.KEY_BOOK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<BookRecord>> getKeys() {
		return Arrays.<UniqueKey<BookRecord>>asList(Keys.KEY_BOOK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<BookRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<BookRecord, ?>>asList(Keys.FK_T_BOOK_AUTHOR_ID, Keys.FK_T_BOOK_CO_AUTHOR_ID);
	}
}
